### ISSUE TITLE
UserAccessManagerImpl is not handling removal of old data

### ISSUE THREAD

**Issue by rsvoboda** [jirban/jirban-jira#106]
UserAccessManagerImpl is not handling removal of old data, /access-log displays only 1000 records
`UserAccess[] accesses = activeObjects.find(UserAccess.class, Query.select().order("TIME desc").limit(1000));`

Amount of stored data should be limited, what about 2000 or 5000 records if we would need that data someday ?

**Comment by kabir** [comment]
The idea is to have a better query facility eventually, but I agree it should be possible to configure some kind of limit. E.g by max time or max entries.

**Comment by kabir** [comment]
Moved to https://github.com/overbaard/overbaard/issues/7
