### ISSUE TITLE
Move to Yarn: A new package manager for JavaScript by Facebook

### ISSUE THREAD

**Issue by rsvoboda** [jirban/jirban-jira#113]
Yarn is compatible with npm, adds some benefits
https://yarnpkg.com/
http://www.adam-bien.com/roller/abien/entry/speed_comparison_yarns_vs_npm

Offline Mode
If you've installed a package before, you can install it again without any internet connection.

Deterministic
The same dependencies will be installed the same exact way across every machine regardless of install order.

Network Performance
Yarn efficiently queues up requests and avoids request waterfalls in order to maximize network utilization.

Multiple Registries
Install any package from either npm or Bower and keep your package workflow the same.

Network Resilience
A single request failing won't cause an install to fail. Requests are retried upon failure.

Flat Mode
Resolve mismatching versions of dependencies to a single version to avoid creating duplicates.

**Comment by rsvoboda** [comment]
https://yarnpkg.com/en/docs/migrating-from-npm
https://yarnpkg.com/en/docs/cli/

**Comment by kabir** [comment]
Will it still work with the maven plugin?

**Comment by rsvoboda** [comment]
frontend-maven-plugin - https://github.com/eirslett/frontend-maven-plugin
If you prefer Yarn over NPM for your node package fetching, this plugin can also download Node and Yarn and then run yarn install for your project.

https://github.com/eirslett/frontend-maven-plugin/issues/490 Support for yarn

**Comment by kabir** [comment]
Done by https://github.com/jirban/jirban-jira/pull/114
