### ISSUE TITLE
Run UI in webworker

### ISSUE THREAD

**Issue by kabir** [jirban/jirban-jira#122]
This should improve UI responsiveness.

Most examples I have seen so far are when using the standard SystemJS module system, while we are using webpack. Here are some links relating to webpack. None of them really work, but we should keep investigating:
* http://stackoverflow.com/questions/40130142/run-angular-2-app-in-web-worker-using-webpack
* https://github.com/alexpods/angular2-universal-starter a bit too advanced to understand what is going on
    * http://www.javascripttuts.com/analysing-the-angular-2-universal-starter-kit/
* https://medium.com/@MatthewDeNobrega/angular2-with-webpack-tips-and-tricks-eef53fb26bd3#.mxsfpzogt
* http://darrinholst.com/blog/2016/09/11/web-worker/

**Comment by rsvoboda** [comment]
+1 for this effort

**Comment by kabir** [comment]
Investigation shows this is not possible if you want to have access to the dom, which as far as I can tell I need

**Comment by rsvoboda** [comment]
So it's either dom access or performance ?

Can you push just some parts to webworker or it would complicate Overbård too much ?

**Comment by kabir** [comment]
I have some vague ideas to put the view model calculation into WW, but have yet to play with it.
