### ISSUE TITLE
Swimlanes/filters for Fix Version

### ISSUE THREAD

**Issue by kabir** [jirban/jirban-jira#123]

**Comment by rsvoboda** [comment]
I guess you plan to use check-boxes to select Fix Versions.

What about extending it to support expression like 7.1.0.DR* ?

[edit] Sometimes all Fix Versions are yet not defined in the time of creation of the board. This way it could be more generic.

**Comment by kabir** [comment]
This will work similar to components as outlined in https://github.com/jirban/jirban-jira/issues/121#issuecomment-267003436. The Fix Version list will be populated by the data in the issues. For now we will use checkboxes, later we can think of something better :)
