### ISSUE TITLE
Possibility to invert filter selection

### ISSUE THREAD

**Issue by kabir** [jirban/jirban-jira#124]
If I want to select e.g. all components apart from Transactions, I currently need to select a lot of boxes.

It would be better to select just the unwanted component (Transactions) and then press 'invert' to get all the others

**Comment by rsvoboda** [comment]
What about a bit simpler approach for filters:
 * Select All
 * Select None

![screenshot from 2016-12-14 12-00-26](https://cloud.githubusercontent.com/assets/925259/21179655/4f5e2484-c1f5-11e6-804b-82d260f897f8.png)

**Comment by kabir** [comment]
Select All is a good idea. You can click on the 'Component Filter' header to clear all. Although perhaps that is not super-obvious. So since we are adding more links, we could do something like

Header (e.g. 'Component Filter' in this case)
all | clear | invert
list of checkboxes

**Comment by rsvoboda** [comment]
'all | clear | invert' is good idea 

I would keep it on the same line with 'ABC... Filter' if possible

**Comment by rsvoboda** [comment]
New line can work too, it would be easier for impl and to prevent UX issues with overlaps in case of long headers
