### ISSUE TITLE
Swimlanes with no issues should not show backlog text in collapsed backlog column

### ISSUE THREAD

**Issue by kabir** [jirban/jirban-jira#129]
By having it as it is at present, we end up having to collapse a lot of empty swimlanes to get meaningful data.

<img width="706" alt="screen shot 2017-01-04 at 15 12 40" src="https://cloud.githubusercontent.com/assets/49927/21646959/4fa5417e-d290-11e6-803e-97bef81328c7.png">

We should either not show the backlog text in the left column, or we should perhaps totally hide the swimlanes with no data. If we go with the second option, perhaps that could be made an option in the control panel

**Comment by rsvoboda** [comment]
How it looks when you collapse e.g. Analysis ? I guess similar to Backlog case ...
  https://issues.jboss.org/jirban/index.html#/board?board=EAP7-curr&visible=12,13,14,15,16,17,18&swimlane=assignee

When swimlanes are enabled I wouldn't show text for collapsed columns. You have info in tooltip when you move cursor over the heading.

**Comment by kabir** [comment]
Yes, collapsing analysis is the same. So we can trim down the size by not showing the text. 

Still if there are 200 assignees, and you have selected swimlane by assignee, and filter for a component which only has 10 assignees, you end up with a lot of noise/empty swimlanes.

**Comment by rsvoboda** [comment]
I think first step is to remove the text in swimlanes.

Second step can be checkbox 'Show empty swimlanes' in settings, by default I would keep it selected.
