### ISSUE TITLE
Add support to add comment to JIRA from context menu 

### ISSUE THREAD

**Issue by rsvoboda** [jirban/jirban-jira#13]
Add support to add comment to JIRA from context menu (under triple-dot in the right top corner)

Side-note: second click on ... should probably close the window

**Comment by rsvoboda** [comment]
Text area is wider than header of the window, see 
![screenshot from 2016-05-31 11-57-03](https://cloud.githubusercontent.com/assets/925259/15670706/1b91807e-2727-11e6-8152-34f10ce36a61.png)

When comment is added it would be nice to have some temporary message (for 5 seconds) shown in blue upper part of the board saying something like "Comment added to EAPDS-6" ... and EAPDS-6 is clickable ... something similar to core JIRA when you create new issue. Motivation is to have chance to check where the comment was added ;)

**Comment by kabir** [comment]
@rsvoboda I have fixed the textarea size and uploaded to the staging server. Does it look better now? I'll do the confirmation message next.

**Comment by rsvoboda** [comment]
It's better, just the Save button jumps out in the bottom
![screenshot from 2016-05-31 17-21-17](https://cloud.githubusercontent.com/assets/925259/15680019/51da9a6c-2754-11e6-9efd-d856fd8e2d0f.png)

**Comment by kabir** [comment]
@rsvoboda I uploaded another version. Is it ok now? I also added the success message/notification to the top right of the blue bar. It stays there for 5 seconds which should give time to click on the link.

**Comment by rsvoboda** [comment]
Notification is nice, really like it.

The last thing is that Save button, it's a bit crippled on my FF where I have minimum font size 13.
On Chrome the Save button looks fine, on FF I reset the minimum font size and checked the "add comment" window. It's a bit better, but still the button is much wider comparing to chrome and text in not vertically centered.  Screenshot is taken with minimal font size 13.
![screenshot from 2016-06-01 09-12-33](https://cloud.githubusercontent.com/assets/925259/15701211/2f1f26e8-27d9-11e6-9fa0-6061c3f9b338.png)

Now you feel the pain of web development with optimizations for 2 browsers, maybe 3 if you are using Safari ;)

**Comment by kabir** [comment]
I've adjusted the button as good as I can. It still looks weird on Firefox on Fedora though, but it is all I can do at this stage. Once I upgraded to 46.0.1 I could reproduce the problem, but it looked fine on 43.x.x

**Comment by rsvoboda** [comment]
I got better result when I tweaked CSS  ( .comment-button[_ngcontent-bjr-7]) via webdeveloper tools in browser.
I removed padding: 3px 6px; 
I added just padding-top: 3px;

It looked fine on both FF and Chrome on my Fedora 23

**Comment by kabir** [comment]
Thanks, I've merged that to master. It will be part of the next plugin upload
