### ISSUE TITLE
filtering by tester while using swimlanes shows swimlanes for all testers

### ISSUE THREAD

**Issue by rhatlapa** [jirban/jirban-jira#143]
When defining swimlanes by tester field and at the same time filtering to only specific testers, still swimlanes for all testers are shown instead of only for the ones defined.

**Comment by rhatlapa** [comment]
I guess it is not only issue with testers but rather for any field which is at the same time being filtered on and put to swimlines

**Comment by kabir** [comment]
Master does not seem to have this problem, but I have applied it to 2.0.3 since this was a problem in 2.0.2
