### ISSUE TITLE
Provide user-guide and development-guide

### ISSUE THREAD

**Issue by rsvoboda** [jirban/jirban-jira#16]
Provide user-guide and development-guide to help with jirban-jira adoption

**Comment by kabir** [comment]
The README.md is updated now to explain how to set up the development environment

**Comment by rsvoboda** [comment]
Text looks good. I would like to see some end-user section too, because people will ask how to get to the board, how to share boards, how to move item from one column to another etc.

**Comment by kabir** [comment]
I have added a user guide at https://github.com/jirban/jirban-jira/tree/master/userguide (also linked to from the main README)

**Comment by rsvoboda** [comment]
Created #25 for link fix.
