### ISSUE TITLE
Be able to link to a board with customized view when some columns are "minimized"

### ISSUE THREAD

**Issue by rsvoboda** [jirban/jirban-jira#17]
Be able to link to a board with customized view when some columns are "minimized" (by clicking on their header) This is enhancement of #7 task.

Example - full view on Development and QA columns, other columns are minimized, but accessible on one click.

**Comment by kabir** [comment]
@rsvoboda This has been done and merged, although not uploaded yet (I seem to have lost rights to upload to the staging instance). While here I also did the same for the swimlane headers, so you can now link to a board with certain states and swimlanes collapsed.

**Comment by rsvoboda** [comment]
Looks good :thumbsup:
