### ISSUE TITLE
Some state transitions require data

### ISSUE THREAD

**Issue by kabir** [jirban/jirban-jira#2]
Some transitions require data. This information is available in the output of

https://myjira.com/rest/api/2/issue/<IssueKey>/transitions?expand=transitions.fields

and can be used to populate a dialog on the client.

QE have pointed out that a comment is needed when moving to verified

**Comment by kabir** [comment]
@rsvoboda Jira has been modified to request a comment when moving to the Verified state. Jirban work to follow.

**Comment by rsvoboda** [comment]
Can confirm that comment window now pops up in JIRA, checked with https://issues.jboss.org/browse/EAP7-502

**Comment by kabir** [comment]
Moved to https://github.com/overbaard/overbaard/issues/2
