### ISSUE TITLE
Look into renaming the Jira transitions

### ISSUE THREAD

**Issue by kabir** [jirban/jirban-jira#29]
to e.g.  "Move to 'Closed'" rather than the current "Closed"

**Comment by kabir** [comment]
All transitions have been renamed in Jira. However, although the "Backlog" transition has been renamed to "Move to 'Backlog'", its button in issues still appears as "Backlog". Perhaps this is something hardcoded in Jira?

**Comment by hyperlamacz** [comment]
The "Move to Backlog" is in the Workflow menu, no problem with that.

Now, when looking under the workflow menu how it looks like in reality I start to think this may have not been a good idea. Let us discuss further.

**Comment by kabir** [comment]
@hyperlamacz Yes, things get truncated a bit. And it seems to truncate by appending '&...' (rather than simply '...')
