### ISSUE TITLE
Board Settings UI adjustments

### ISSUE THREAD

**Issue by rsvoboda** [jirban/jirban-jira#32]
I noticed few things with updated Board Settings dialog.
- Dialog jump away from the settings window, I suggest to stretch out it a bit to the settings icon
- I think there should be wider margin before columns
- Filter items should have bigger top/bottom margin
- Link / Swimlane / Issue Detail may have bigger top/bottom margin too

ds
![screenshot from 2016-06-07 16-33-01](https://cloud.githubusercontent.com/assets/925259/15862166/16fdc3a8-2ccf-11e6-9680-8fa907e963dc.png)

**Comment by kabir** [comment]
When you say "Filter items should have bigger top/bottom margin" Do you mean e.g Project, Issue Type etc. and Critical, Blocker etc.? i.e. the lists?

**Comment by rsvoboda** [comment]
I mean items in middle column - Project, Issue Type, Priority, Assignee, Component

**Comment by kabir** [comment]
Uploaded to staging

**Comment by rsvoboda** [comment]
Stage looks good, the only concern I have is top/bottom margin for items in the middle column.
It could have it still a bot bigger. But this can be revisited later, new filters can be requested, additional changes, etc.
