### ISSUE TITLE
Provide information about version of jirban

### ISSUE THREAD

**Issue by rsvoboda** [jirban/jirban-jira#49]
Provide information about version / build date of jirban. Currently there is no such information.

This information could be placed in top header next to Boards Config - new item About.
Or version / build date info could be placed in Board Settings dialog too.

**Comment by kabir** [comment]
I think we can probably get away putting it in the footer of the boards list, and on the config page. i.e. everywhere apart from the board itself?

**Comment by rsvoboda** [comment]
It could work too. My idea was to get easy access to that information from the board.
Have it available in Boards and Config pages seems to be sufficient, proceed with the footer ;)

**Comment by kabir** [comment]
I've merged a fix including the maven version in the footer. Holding off on the build date for now, due to laziness reasons wrt formatting the date :)
