### ISSUE TITLE
'Immediate swimlane view' / wait icon 

### ISSUE THREAD

**Issue by rsvoboda** [jirban/jirban-jira#53]
When I select swimlane in board settings, it takes like 5 seconds to refresh the page according the swimlane settings. I'd like to see the change immediately. I think you have some timer to refresh the page and pull the changes, right ?

'Immediate swimlane view' - seems not to be possible atm, it needs to go through all issues and build up the table. Perhaps possible when browser caches more things, but that means more memory.

Wait icon can be the solution for now. It can give some feedback that something is happening.

**Comment by kabir** [comment]
Just using ProgressErrorService doesn't work, probably because both the processing and the UI update from ProgressErrorService happen in the same thread, so the ProgressErrorService change is not picked up. Using NgZone.run() doesn't work for me either

**Comment by kabir** [comment]
I believe the Overbård performance improvements deal with this
