### ISSUE TITLE
Capture the state of board and compare with another snapshot

### ISSUE THREAD

**Issue by rsvoboda** [jirban/jirban-jira#60]
Provide functionality to:
- capture current state in machinely processable format - e.g. JSON
- compare states of JIRAs between two snapshots

Suggested format of the comparison is provided here https://docs.google.com/spreadsheets/d/1UgiXC-oLPcx7oU5saZKDEL12yxIasYDOBINVU6OJKtg/edit#gid=0

JSON file would need stable format so we can run comparison for quite old (months) snapshot vs. the latest. Or maybe some upgrade procedure for older JSON dumps

**Comment by kabir** [comment]
An upgrade procedure for older JSON dumps sounds like a good idea

**Comment by kabir** [comment]
If this is still important to you please open in https://github.com/overbaard/overbaard/issues
