### ISSUE TITLE
Board settings don't survive F5 page refresh

### ISSUE THREAD

**Issue by mchoma** [jirban/jirban-jira#67]
When I set Component Security in Board Settings I can see filtered issues, but when I pres F5 filter is cleared and I see all Jiras again.

Workaround: In the settings dialog though there is a Link field which gets updated as you tweak settings. You can copy that and use for bookmarks etc.

**Comment by kabir** [comment]
The new angular router now allows the use of history.replaceState(), so this has been added. The browser address bar is now updates as the view settings are changed
