### ISSUE TITLE
 New record in access-log is added when I click on Backlog to show it or hide it

### ISSUE THREAD

**Issue by rsvoboda** [jirban/jirban-jira#70]
I noticed that when I click on Backlog new record in access-log is added

**Comment by rsvoboda** [comment]
#69 might solve the issue if we can get rid of the round trip to the server to load/unload the backlog

**Comment by rsvoboda** [comment]
Thing to consider is whether you differentiate session / user-agent 
I may do something on FF and something on Chrome : Should I have 2 records or just 1 ? I would say 2 :)

**Comment by kabir** [comment]
^^ is in response to my idea to only add the access log entry if the user has not accessed the board in the last 30 minutes or so.

If we actually store the session id in the database, we can probably increase the 'timeout' somewhat. There is still a chance that session ids get reused, but a combination of that and say 4 hours should help with the duplicate entries.
