### ISSUE TITLE
Provide compiled binaries

### ISSUE THREAD

**Issue by rsvoboda** [jirban/jirban-jira#75]
Provide compiled binaries in https://github.com/jirban/jirban-jira/releases

Some help: 
- https://help.github.com/articles/distributing-large-binaries/
- https://help.github.com/articles/about-releases/

**Comment by kabir** [comment]
Here it is for 1.0.9 https://github.com/jirban/jirban-jira/releases/tag/1.0.9

**Comment by rsvoboda** [comment]
Are you using https://help.github.com/articles/creating-releases/ procedure ?

**Comment by rsvoboda** [comment]
Maybe some day it would be nice to describe full release procedure ...

**Comment by kabir** [comment]
Here we go
1) Tag the release and push the tag
2) Build the plugin jar (using `atlas-package` -Djirban.ui)
3) Go to https://github.com/jirban/jirban-jira
4) Click on 'releases'
5) Click on 'Draft a new release'
6) Enter the tag from 1)
7) Enter a title and description
8) Drag the jar created in 2) to the bottom of the page
7) Click 'Publish release'

**Comment by rsvoboda** [comment]
Thanks!
