### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by rsvoboda** [jirban/jirban-jira#87]
Running mvn clean integration-test

```
Tests in error: 
  testSomething(it.org.jirban.jira.servlet.RestServletFuncTest): Not Found
  No tests found in class [it.org.jirban.jira.JiraFacadeWiredTest]: No tests found in class [it.org.jirban.jira.JiraFacadeWiredTest]
```

Please ignore / fix / enhance

**Comment by rsvoboda** [comment]
RestServletFuncTest fails at `String responseBody = httpClient.execute(httpget, responseHandler);`
So the accessed url seems to be incorrect.

**Comment by kabir** [comment]
RestServletFuncTest was autogenerated by the atlassian archetypes when adding the servlet I used when doing the initial version of Jirban where it was hosted outside of Jira and got the data via rest api calls to Jira. To run this in Jira I needed to migrate the RestServlet to the current RestEndpoint. So this test can be removed.

Similarly JiraFacadeWiredTest also got added for me, but never used. I'd love to find a way to get rid of the jirban-jira-xxx-tests.jar generation and deployment though.

**Comment by rsvoboda** [comment]
Resolved in https://github.com/jirban/jirban-jira/commit/7ce949063cae7da5db08802d88de6adbbfb46d15

> I'd love to find a way to get rid of the jirban-jira-xxx-tests.jar generation and deployment though.

It seems the only way is to run {{atlas-package -Dmaven.test.skip=true}} as QuickReload thingy looking at *.jar in target directory.
jirban-jira-xxx-tests.jar  is created by maven-jira-plugin

**Comment by rsvoboda** [comment]
Tried to look at Atlassian  documents and JIRA for maven plugins but with no luck, closing.

Explored resources:
https://ecosystem.atlassian.net/projects/AMPS/
https://developer.atlassian.com/docs/advanced-topics/working-with-maven/using-the-amps-maven-plugin-directly
https://developer.atlassian.com/docs/developer-tools/working-with-the-sdk/about-amps-build-options/amps-build-configuration-reference
